# https://en.wikipedia.org/wiki/List_of_cuisines_of_the_Americas#Central_American_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "central america"
    adj = "central american"
  [translation.es]
    term = "américa central"
    adj = "centroamericana"
