# https://en.wikipedia.org/wiki/List_of_cuisines_of_the_Americas#Latin_American_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "latin america"
    adj = "latin american"
  [translation.es]
    term = "américa latina"
    adj = "latinoamericana"
