# https://en.wikipedia.org/wiki/List_of_cuisines_of_the_Americas#North_American_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "north america"
    adj = "north american"
  [translation.es]
    term = "américa del norte"
    adj = "norteamericana"
