# https://en.wikipedia.org/wiki/List_of_cuisines_of_the_Americas#South_American_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "south america"
    adj = "south american"
  [translation.es]
    term = "sudamérica"
    adj = "sudamericana"
