version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    working_directory: ~/Food-Data

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install toml

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 testSuite/testSuite.py
