# https://en.wikipedia.org/wiki/List_of_Asian_cuisines#Central_Asian_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "central asia"
    adj = "central asian"
  [translation.es]
    term = "asia central"
    adj = "asiática central"
