# https://en.wikipedia.org/wiki/List_of_Asian_cuisines#East_Asian_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "east asia"
    adj = "east asian"
  [translation.es]
    term = "asia oriental"
    adj = "asiática oriental"
