# https://en.wikipedia.org/wiki/List_of_Asian_cuisines#Southeast_Asian_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "southeast asia"
    adj = "southeast asian"
  [translation.es]
    term = "sudeste asiático"
    adj = "asiática sudoriental"
