# https://en.wikipedia.org/wiki/List_of_Asian_cuisines#South_Asian_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "south asia"
    adj = "south asian"
  [translation.es]
    term = "sur de asia"
    adj = "sur asiatica"
