# https://en.wikipedia.org/wiki/List_of_Asian_cuisines#West_Asian_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "west asia"
    adj = "west asian"
  [translation.es]
    term = "asia occidental"
    adj = "asiática occidental"
