# https://en.wikipedia.org/wiki/List_of_European_cuisines#Central_European_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "central europe"
    adj = "central european"
  [translation.es]
    term = "europa central"
    adj = "europea central"
