# https://en.wikipedia.org/wiki/List_of_European_cuisines#Eastern_European_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "eastern europe"
    adj = "eastern european"
  [translation.es]
    term = "europa oriental"
    adj = "europea oriental"
