# https://en.wikipedia.org/wiki/List_of_European_cuisines#Northern_European_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "northern europe"
    adj = "northern european"
  [translation.es]
    term = "europa del norte"
    adj = "europea del norte"
