# https://en.wikipedia.org/wiki/List_of_European_cuisines#Southern_European_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "southern europe"
    adj = "southern european"
  [translation.es]
    term = "europa meridional"
    adj = "europea meridional"
