# https://en.wikipedia.org/wiki/List_of_European_cuisines#Western_European_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "western europe"
    adj = "western european"
  [translation.es]
    term = "europa occidental"
    adj = "europea occidental"
