# https://en.wikipedia.org/wiki/List_of_African_cuisines#East_African_cuisine

type = "subregion"

[translation]
  [translation.en]
    term = "east africa"
    adj = "east african"
  [translation.es]
    term = "áfrica oriental"
    adj = "africana oriental"
