# https://en.wikipedia.org/wiki/List_of_African_cuisines#North_African_cuisine
# https://en.wikipedia.org/wiki/African_cuisine#North_Africa

type = "subregion"

[translation]
  [translation.en]
    term = "north africa"
    adj = "north african"
