# https://en.wikipedia.org/wiki/Pork
exclude-diet = ["kosher", "halal"]

[translation]
  [translation.en]
    term = "pork"
  [translation.fr]
    term = "viande de porc"
  [translation.es]
    term = "carne de cerdo"
