# https://en.wikipedia.org/wiki/Oceanic_cuisine
# https://en.wikipedia.org/wiki/Oceania
# https://en.wikipedia.org/wiki/Australasia

type = "subregion"

[translation]
  [translation.en]
    term = "australasia"
    adj = "australasian"
  [translation.es]
    term = "australasia"
    adj = "australasiana"
