# https://en.wikipedia.org/wiki/Oceanic_cuisine
# https://en.wikipedia.org/wiki/Oceania

type = "subregion"

[translation]
  [translation.en]
    term = "melanesia"
    adj = "melanesian"
  [translation.es]
    term = "melanesia"
    adj = "melanesio"
