# https://en.wikipedia.org/wiki/Oceanic_cuisine
# https://en.wikipedia.org/wiki/Oceania

type = "subregion"

[translation]
  [translation.en]
    term = "micronesia"
    adj = "micronesian"
  [translation.es]
    term = "micronesia"
    adj = "micronesia"
