# https://en.wikipedia.org/wiki/Oceanic_cuisine
# https://en.wikipedia.org/wiki/Oceania

type = "subregion"

[translation]
  [translation.en]
    term = "polynesia"
    adj = "polynesian"
  [translation.es]
    term = "polinesia"
    adj = "polinesio"
