# https://en.wikipedia.org/wiki/Vegetable#Terminology (Culinary Vegetable)
exclude-diet = ["carnivoroust", "ketogenic"]

[translation]
  [translation.en]
    term = "vegetable"
  [translation.fr]
    term = "légume"
